#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Oct 23 20:47:33 KST 2025
# SW Build 5164865 on Thu Sep  5 14:36:28 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_fir_filter_behav -key {Behavioral:sim_1:Functional:tb_fir_filter} -tclbatch tb_fir_filter.tcl -log simulate.log"
xsim tb_fir_filter_behav -key {Behavioral:sim_1:Functional:tb_fir_filter} -tclbatch tb_fir_filter.tcl -log simulate.log

